language: node_js
node_js:
  - "12"
sudo: required
script:
  - ./configure
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - ./ninja
